### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by AlistairMcKinnon** [MBuchalik/cordova-plugin-ios-permissions#5]
Hi
I've used the plug in but it comes up in German and when I take a picture it changes the captions of "Use photo" and "Cancel" to German.
How do I specify English
Thanks
Alistair

**Comment by MBuchalik** [comment]
This plugin definitely doesn't change the captions such as "Cancel" so I assume that some setting is missing in your config.xml. Have you tried to define CFBundleLocalizations? If not, adding something like the following to your config.xml might help you.

``` XML
<config-file target="*-Info.plist" parent="CFBundleLocalizations">
	<array>
		<string>en</string>
		<string>de</string>
	</array>
</config-file>
```

If it doesn't help, please add your config.xml here so that I can have a look at it (please only include the necessary plugins so that we can be sure it is really caused by my plugin). Which version of this plugin are you using?

**Comment by AlistairMcKinnon** [comment]
Hi

Here is the zip of the config.xml file

[config.zip](https://github.com/MBuchalik/cordova-plugin-ios-permissions/files/2207275/config.zip)

It is using plug in reference
https://github.com/MBuchalik/cordova-plugin-ios-permissions.git#v1.1.1

which only seems to have German and Portuguese?

Thanks

Alistair

**Comment by MBuchalik** [comment]
Hi,

i had a look at your config.xml and had the same problem. After switching the PGB version to 7.1.0 using
``` xml
<preference name="phonegap-version" value="cli-7.1.0" />
```
the problems were gone. Could you test that?

Btw: The English part can be found in the plugin.xml, so the currently supported languages are German, Portuguese and English.

**Comment by AlistairMcKinnon** [comment]
Yes that works.
Many thanks for your help!
Alistair
